apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: dev
spec:
  selector:
    app: task-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8001 # service port
      targetPort: 8001 # container port

