apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000 # the port other services will use
      targetPort: 8000 # the port inside the container
      nodePort: 30001
  # type: ClusterIP # default, internal cluster communication
