apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://zaryab:zaryab@cluster0.njbce6r.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "your_jwt_secret_key"
  REDIS_URL: "rediss://default:AbyQAAIncDEwOTg5NTliZDlkYWY0ZTA0YjFhZDNhMGJkMmRlODYyZXAxNDgyNzI@intent-flounder-48272.upstash.io:6379"
