apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: dev
spec:
  selector:
    app: job-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8002 # service port
      targetPort: 8002 # container port

