apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  selector:
    app: job-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8002 # internal cluster port
      targetPort: 8002 # container port
      nodePort: 30003 # exposed externally
