apiVersion: v1
kind: Service
metadata:
  name: import-service
spec:
  selector:
    app: import-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8003 # internal cluster port
      targetPort: 8003 # container port
      nodePort: 30004 # exposed externally
