apiVersion: v1
kind: Service
metadata:
  name: import-service
  namespace: dev
spec:
  selector:
    app: import-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8003 # service port
      targetPort: 8003 # container port

